language: python
sudo: false
cache: pip
dist: xenial
install:
  - pip install coveralls>=1.1 tox
script:
  - tox
after_success:
  coveralls
matrix:
  include:
   - env: TOXENV=py36
     python: '3.6.7'