site_name: Django EVE Online Connector
# Theme Configuration
theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'white'

# Navigiation
nav:
  - Overview: index.md
  - Features: features.md 
  - User Guide: user_guide.md


# Extensions
markdown_extensions:
    - admonition