# Generated by Django 2.2.13 on 2020-09-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_connector', '0029_load_required_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='evetoken',
            name='invalidated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='evetoken',
            name='requested_scopes',
            field=models.ManyToManyField(blank=True, related_name='requested_scopes', to='django_eveonline_connector.EveScope'),
        ),
        migrations.AlterField(
            model_name='evescope',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
