# Generated by Django 2.2.13 on 2020-09-21 19:07

from django.db import migrations, models
import django_eveonline_connector.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_connector', '0030_auto_20200921_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evetoken',
            name='requested_scopes',
            field=models.ManyToManyField(blank=True, default=django_eveonline_connector.models.EveScope.get_required, related_name='requested_scopes', to='django_eveonline_connector.EveScope'),
        ),
    ]
