# Generated by Django 2.2.13 on 2020-11-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_connector', '0039_auto_20201026_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evecharacter',
            options={'permissions': [('view_corporation_characters', 'Can view characters of same corporation'), ('view_alliance_characters', 'Can view characters of same alliance'), ('view_all_characters', 'Can view all characters')]},
        ),
    ]
