# Generated by Django 2.2.13 on 2020-11-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_connector', '0040_auto_20201121_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evetransaction',
            name='location_name',
            field=models.CharField(max_length=128),
        ),
    ]
