# Generated by Django 2.2.13 on 2021-02-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_connector', '0042_auto_20210210_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveasset',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evecontract',
            name='issuer_corporation_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evetransaction',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
    ]
